apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
#  local:
#    push: false
  googleCloudBuild:
    projectId: ticketing-294223
  artifacts:
    - image: eu.gcr.io/ticketing-294223/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/ticketing-294223/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
         manual:
          - src: '**/*.js'
            dest: .
    - image: eu.gcr.io/ticketing-294223/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
    - image: eu.gcr.io/ticketing-294223/orders
      context: orders
      docker:
          dockerfile: Dockerfile
      sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
    - image: eu.gcr.io/ticketing-294223/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/ticketing-294223/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

