
name: Build and Deploy manifests service to GKE

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

env:
  PROJECT_ID: ticketing-294223
  GKE_CLUSTER: gke-my-first-cluster-1-default-pool-cf3a825e-26w3    
  GKE_ZONE: europe-west1-b  
  DEPLOYMENT_NAME: deploy-manifests
  IMAGE: manifests

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GKE_KEY }}
        project_id: $PROJECT_ID

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"


    # Deploy k8s manifests to the GKE cluster
    - name: Deploy
      run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod

